# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='server.proto',
  package='org.bankatm.grpc',
  syntax='proto3',
  serialized_options=b'P\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cserver.proto\x12\x10org.bankatm.grpc\"@\n\x1avalidateCredentialsRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"A\n\x1bvalidateCredentialsResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12\x12\n\nclientName\x18\x02 \x01(\t\",\n\x18getAccountBalanceRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"3\n\x19getAccountBalanceResponse\x12\x16\n\x0e\x61\x63\x63ountBalance\x18\x01 \x01(\x01\"2\n\x0e\x64\x65positRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x03\"!\n\x0f\x64\x65positResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\"3\n\x0fwithdrawRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\"\"\n\x10withdrawResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\x32\x90\x01\n\x1avalidateCredentialsService\x12r\n\x13validateCredentials\x12,.org.bankatm.grpc.validateCredentialsRequest\x1a-.org.bankatm.grpc.validateCredentialsResponse2\x88\x01\n\x18getAccountBalanceService\x12l\n\x11getAccountBalance\x12*.org.bankatm.grpc.getAccountBalanceRequest\x1a+.org.bankatm.grpc.getAccountBalanceResponse2`\n\x0e\x64\x65positService\x12N\n\x07\x64\x65posit\x12 .org.bankatm.grpc.depositRequest\x1a!.org.bankatm.grpc.depositResponse2d\n\x0fwithdrawService\x12Q\n\x08withdraw\x12!.org.bankatm.grpc.withdrawRequest\x1a\".org.bankatm.grpc.withdrawResponseB\x02P\x01\x62\x06proto3'
)




_VALIDATECREDENTIALSREQUEST = _descriptor.Descriptor(
  name='validateCredentialsRequest',
  full_name='org.bankatm.grpc.validateCredentialsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='org.bankatm.grpc.validateCredentialsRequest.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='org.bankatm.grpc.validateCredentialsRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=98,
)


_VALIDATECREDENTIALSRESPONSE = _descriptor.Descriptor(
  name='validateCredentialsResponse',
  full_name='org.bankatm.grpc.validateCredentialsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='org.bankatm.grpc.validateCredentialsResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='clientName', full_name='org.bankatm.grpc.validateCredentialsResponse.clientName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=165,
)


_GETACCOUNTBALANCEREQUEST = _descriptor.Descriptor(
  name='getAccountBalanceRequest',
  full_name='org.bankatm.grpc.getAccountBalanceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='org.bankatm.grpc.getAccountBalanceRequest.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=211,
)


_GETACCOUNTBALANCERESPONSE = _descriptor.Descriptor(
  name='getAccountBalanceResponse',
  full_name='org.bankatm.grpc.getAccountBalanceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='accountBalance', full_name='org.bankatm.grpc.getAccountBalanceResponse.accountBalance', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=264,
)


_DEPOSITREQUEST = _descriptor.Descriptor(
  name='depositRequest',
  full_name='org.bankatm.grpc.depositRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='org.bankatm.grpc.depositRequest.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='amount', full_name='org.bankatm.grpc.depositRequest.amount', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=316,
)


_DEPOSITRESPONSE = _descriptor.Descriptor(
  name='depositResponse',
  full_name='org.bankatm.grpc.depositResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='org.bankatm.grpc.depositResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=318,
  serialized_end=351,
)


_WITHDRAWREQUEST = _descriptor.Descriptor(
  name='withdrawRequest',
  full_name='org.bankatm.grpc.withdrawRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='org.bankatm.grpc.withdrawRequest.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='amount', full_name='org.bankatm.grpc.withdrawRequest.amount', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=353,
  serialized_end=404,
)


_WITHDRAWRESPONSE = _descriptor.Descriptor(
  name='withdrawResponse',
  full_name='org.bankatm.grpc.withdrawResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='org.bankatm.grpc.withdrawResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=406,
  serialized_end=440,
)

DESCRIPTOR.message_types_by_name['validateCredentialsRequest'] = _VALIDATECREDENTIALSREQUEST
DESCRIPTOR.message_types_by_name['validateCredentialsResponse'] = _VALIDATECREDENTIALSRESPONSE
DESCRIPTOR.message_types_by_name['getAccountBalanceRequest'] = _GETACCOUNTBALANCEREQUEST
DESCRIPTOR.message_types_by_name['getAccountBalanceResponse'] = _GETACCOUNTBALANCERESPONSE
DESCRIPTOR.message_types_by_name['depositRequest'] = _DEPOSITREQUEST
DESCRIPTOR.message_types_by_name['depositResponse'] = _DEPOSITRESPONSE
DESCRIPTOR.message_types_by_name['withdrawRequest'] = _WITHDRAWREQUEST
DESCRIPTOR.message_types_by_name['withdrawResponse'] = _WITHDRAWRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

validateCredentialsRequest = _reflection.GeneratedProtocolMessageType('validateCredentialsRequest', (_message.Message,), {
  'DESCRIPTOR' : _VALIDATECREDENTIALSREQUEST,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:org.bankatm.grpc.validateCredentialsRequest)
  })
_sym_db.RegisterMessage(validateCredentialsRequest)

validateCredentialsResponse = _reflection.GeneratedProtocolMessageType('validateCredentialsResponse', (_message.Message,), {
  'DESCRIPTOR' : _VALIDATECREDENTIALSRESPONSE,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:org.bankatm.grpc.validateCredentialsResponse)
  })
_sym_db.RegisterMessage(validateCredentialsResponse)

getAccountBalanceRequest = _reflection.GeneratedProtocolMessageType('getAccountBalanceRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETACCOUNTBALANCEREQUEST,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:org.bankatm.grpc.getAccountBalanceRequest)
  })
_sym_db.RegisterMessage(getAccountBalanceRequest)

getAccountBalanceResponse = _reflection.GeneratedProtocolMessageType('getAccountBalanceResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETACCOUNTBALANCERESPONSE,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:org.bankatm.grpc.getAccountBalanceResponse)
  })
_sym_db.RegisterMessage(getAccountBalanceResponse)

depositRequest = _reflection.GeneratedProtocolMessageType('depositRequest', (_message.Message,), {
  'DESCRIPTOR' : _DEPOSITREQUEST,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:org.bankatm.grpc.depositRequest)
  })
_sym_db.RegisterMessage(depositRequest)

depositResponse = _reflection.GeneratedProtocolMessageType('depositResponse', (_message.Message,), {
  'DESCRIPTOR' : _DEPOSITRESPONSE,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:org.bankatm.grpc.depositResponse)
  })
_sym_db.RegisterMessage(depositResponse)

withdrawRequest = _reflection.GeneratedProtocolMessageType('withdrawRequest', (_message.Message,), {
  'DESCRIPTOR' : _WITHDRAWREQUEST,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:org.bankatm.grpc.withdrawRequest)
  })
_sym_db.RegisterMessage(withdrawRequest)

withdrawResponse = _reflection.GeneratedProtocolMessageType('withdrawResponse', (_message.Message,), {
  'DESCRIPTOR' : _WITHDRAWRESPONSE,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:org.bankatm.grpc.withdrawResponse)
  })
_sym_db.RegisterMessage(withdrawResponse)


DESCRIPTOR._options = None

_VALIDATECREDENTIALSSERVICE = _descriptor.ServiceDescriptor(
  name='validateCredentialsService',
  full_name='org.bankatm.grpc.validateCredentialsService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=443,
  serialized_end=587,
  methods=[
  _descriptor.MethodDescriptor(
    name='validateCredentials',
    full_name='org.bankatm.grpc.validateCredentialsService.validateCredentials',
    index=0,
    containing_service=None,
    input_type=_VALIDATECREDENTIALSREQUEST,
    output_type=_VALIDATECREDENTIALSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_VALIDATECREDENTIALSSERVICE)

DESCRIPTOR.services_by_name['validateCredentialsService'] = _VALIDATECREDENTIALSSERVICE


_GETACCOUNTBALANCESERVICE = _descriptor.ServiceDescriptor(
  name='getAccountBalanceService',
  full_name='org.bankatm.grpc.getAccountBalanceService',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=590,
  serialized_end=726,
  methods=[
  _descriptor.MethodDescriptor(
    name='getAccountBalance',
    full_name='org.bankatm.grpc.getAccountBalanceService.getAccountBalance',
    index=0,
    containing_service=None,
    input_type=_GETACCOUNTBALANCEREQUEST,
    output_type=_GETACCOUNTBALANCERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GETACCOUNTBALANCESERVICE)

DESCRIPTOR.services_by_name['getAccountBalanceService'] = _GETACCOUNTBALANCESERVICE


_DEPOSITSERVICE = _descriptor.ServiceDescriptor(
  name='depositService',
  full_name='org.bankatm.grpc.depositService',
  file=DESCRIPTOR,
  index=2,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=728,
  serialized_end=824,
  methods=[
  _descriptor.MethodDescriptor(
    name='deposit',
    full_name='org.bankatm.grpc.depositService.deposit',
    index=0,
    containing_service=None,
    input_type=_DEPOSITREQUEST,
    output_type=_DEPOSITRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DEPOSITSERVICE)

DESCRIPTOR.services_by_name['depositService'] = _DEPOSITSERVICE


_WITHDRAWSERVICE = _descriptor.ServiceDescriptor(
  name='withdrawService',
  full_name='org.bankatm.grpc.withdrawService',
  file=DESCRIPTOR,
  index=3,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=826,
  serialized_end=926,
  methods=[
  _descriptor.MethodDescriptor(
    name='withdraw',
    full_name='org.bankatm.grpc.withdrawService.withdraw',
    index=0,
    containing_service=None,
    input_type=_WITHDRAWREQUEST,
    output_type=_WITHDRAWRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_WITHDRAWSERVICE)

DESCRIPTOR.services_by_name['withdrawService'] = _WITHDRAWSERVICE

# @@protoc_insertion_point(module_scope)
