// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package org.bankatm.grpc;

public interface depositRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.bankatm.grpc.depositRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>int64 amount = 2;</code>
   * @return The amount.
   */
  long getAmount();
}
