// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package org.bankatm.grpc;

public interface getAccountBalanceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.bankatm.grpc.getAccountBalanceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
