// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package org.bankatm.grpc;

public interface getAccountBalanceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.bankatm.grpc.getAccountBalanceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double accountBalance = 1;</code>
   * @return The accountBalance.
   */
  double getAccountBalance();
}
