// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package org.bankatm.grpc;

public final class Server {
  private Server() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_bankatm_grpc_validateCredentialsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_bankatm_grpc_validateCredentialsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_bankatm_grpc_validateCredentialsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_bankatm_grpc_validateCredentialsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_bankatm_grpc_getAccountBalanceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_bankatm_grpc_getAccountBalanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_bankatm_grpc_getAccountBalanceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_bankatm_grpc_getAccountBalanceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_bankatm_grpc_depositRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_bankatm_grpc_depositRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_bankatm_grpc_depositResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_bankatm_grpc_depositResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_bankatm_grpc_withdrawRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_bankatm_grpc_withdrawRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_bankatm_grpc_withdrawResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_bankatm_grpc_withdrawResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014server.proto\022\020org.bankatm.grpc\"@\n\032vali" +
      "dateCredentialsRequest\022\020\n\010username\030\001 \001(\t" +
      "\022\020\n\010password\030\002 \001(\t\"A\n\033validateCredential" +
      "sResponse\022\016\n\006result\030\001 \001(\010\022\022\n\nclientName\030" +
      "\002 \001(\t\",\n\030getAccountBalanceRequest\022\020\n\010use" +
      "rname\030\001 \001(\t\"3\n\031getAccountBalanceResponse" +
      "\022\026\n\016accountBalance\030\001 \001(\001\"2\n\016depositReque" +
      "st\022\020\n\010username\030\001 \001(\t\022\016\n\006amount\030\002 \001(\003\"!\n\017" +
      "depositResponse\022\016\n\006result\030\001 \001(\010\"3\n\017withd" +
      "rawRequest\022\020\n\010username\030\001 \001(\t\022\016\n\006amount\030\002" +
      " \001(\005\"\"\n\020withdrawResponse\022\016\n\006result\030\001 \001(\010" +
      "2\220\001\n\032validateCredentialsService\022r\n\023valid" +
      "ateCredentials\022,.org.bankatm.grpc.valida" +
      "teCredentialsRequest\032-.org.bankatm.grpc." +
      "validateCredentialsResponse2\210\001\n\030getAccou" +
      "ntBalanceService\022l\n\021getAccountBalance\022*." +
      "org.bankatm.grpc.getAccountBalanceReques" +
      "t\032+.org.bankatm.grpc.getAccountBalanceRe" +
      "sponse2`\n\016depositService\022N\n\007deposit\022 .or" +
      "g.bankatm.grpc.depositRequest\032!.org.bank" +
      "atm.grpc.depositResponse2d\n\017withdrawServ" +
      "ice\022Q\n\010withdraw\022!.org.bankatm.grpc.withd" +
      "rawRequest\032\".org.bankatm.grpc.withdrawRe" +
      "sponseB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_bankatm_grpc_validateCredentialsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_bankatm_grpc_validateCredentialsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_bankatm_grpc_validateCredentialsRequest_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_org_bankatm_grpc_validateCredentialsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_bankatm_grpc_validateCredentialsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_bankatm_grpc_validateCredentialsResponse_descriptor,
        new java.lang.String[] { "Result", "ClientName", });
    internal_static_org_bankatm_grpc_getAccountBalanceRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_bankatm_grpc_getAccountBalanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_bankatm_grpc_getAccountBalanceRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_org_bankatm_grpc_getAccountBalanceResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_org_bankatm_grpc_getAccountBalanceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_bankatm_grpc_getAccountBalanceResponse_descriptor,
        new java.lang.String[] { "AccountBalance", });
    internal_static_org_bankatm_grpc_depositRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_org_bankatm_grpc_depositRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_bankatm_grpc_depositRequest_descriptor,
        new java.lang.String[] { "Username", "Amount", });
    internal_static_org_bankatm_grpc_depositResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_org_bankatm_grpc_depositResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_bankatm_grpc_depositResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_org_bankatm_grpc_withdrawRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_org_bankatm_grpc_withdrawRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_bankatm_grpc_withdrawRequest_descriptor,
        new java.lang.String[] { "Username", "Amount", });
    internal_static_org_bankatm_grpc_withdrawResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_org_bankatm_grpc_withdrawResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_bankatm_grpc_withdrawResponse_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
