// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package org.bankatm.grpc;

public interface withdrawResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.bankatm.grpc.withdrawResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool result = 1;</code>
   * @return The result.
   */
  boolean getResult();
}
